apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: microservices
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: microservices-demo
    app.kubernetes.io/managed-by: kustomize
type: Opaque
data:
  # base64 encoded "admin" — override in production overlays
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
